/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bueta_cosico_lspunavigation;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import java.awt.event.MouseEvent;

/**
 *
 * @author Shinozaki
 */
public class FrmCCS_Bueta_Cosico extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCCS_Bueta_Cosico.class.getName());

    /**
     * Creates new form FrmCCS_Bueta_Cosico
     */
    public FrmCCS_Bueta_Cosico() {
        this.setUndecorated(true);
        initComponents();
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/bueta_cosico_lspunavigation/images/ccs.png"));
        Image img = icon.getImage().getScaledInstance(400, 300, Image.SCALE_SMOOTH);
        ccsimg.setIcon(new ImageIcon(img));
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        ThemeManager.applyTheme(ThemeManager.currentTheme); // Apply current theme
        updateTheme();
        
        addHover(ccspanel1);
        addHover(ccspanel2);
        addHover(ccspanel3);
        addHover(ccspanel4);
    }
   
        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        ccsbodypanel = new javax.swing.JPanel();
        ccsheaderpanel = new javax.swing.JPanel();
        ccsheaderlbl = new javax.swing.JLabel();
        ccsbackbtn = new javax.swing.JButton();
        ccsminimizebtn = new javax.swing.JButton();
        ccsclosebtn = new javax.swing.JButton();
        ccsfooterpanel = new javax.swing.JPanel();
        ccsfooterlbl = new javax.swing.JLabel();
        ccspanel1 = new ShadowRoundedPanel(20);
        ccslbl1 = new javax.swing.JLabel();
        ccslbl2 = new javax.swing.JLabel();
        ccsimg = new javax.swing.JLabel();
        ccspanel2 = new ShadowRoundedPanel(20);
        ccslbl3 = new javax.swing.JLabel();
        ccslbl4 = new javax.swing.JLabel();
        ccspanel3 = new ShadowRoundedPanel(20);
        ccslbl5 = new javax.swing.JLabel();
        ccslbl6 = new javax.swing.JLabel();
        ccspanel4 = new ShadowRoundedPanel(20);
        ccslbl7 = new javax.swing.JLabel();
        ccslbl8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(245, 245, 245));

        ccsheaderpanel.setBackground(new java.awt.Color(1, 51, 153));
        ccsheaderpanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, -20, 0));

        ccsheaderlbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        ccsheaderlbl.setForeground(new java.awt.Color(255, 255, 255));
        ccsheaderlbl.setText("SOME COLLEGES IN LSPU - Bueta_Cosico");

        ccsbackbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ccsbackbtn.setForeground(new java.awt.Color(1, 51, 153));
        ccsbackbtn.setText("BACK TO MAIN MENU");
        ccsbackbtn.setFocusPainted(false);
        ccsbackbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccsbackbtnActionPerformed(evt);
            }
        });

        ccsminimizebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ccsminimizebtn.setForeground(new java.awt.Color(1, 51, 153));
        ccsminimizebtn.setText("—");
        ccsminimizebtn.setFocusPainted(false);
        ccsminimizebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccsminimizebtnActionPerformed(evt);
            }
        });

        ccsclosebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ccsclosebtn.setForeground(new java.awt.Color(1, 51, 153));
        ccsclosebtn.setText("✕");
        ccsclosebtn.setFocusPainted(false);
        ccsclosebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccsclosebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ccsheaderpanelLayout = new javax.swing.GroupLayout(ccsheaderpanel);
        ccsheaderpanel.setLayout(ccsheaderpanelLayout);
        ccsheaderpanelLayout.setHorizontalGroup(
            ccsheaderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ccsheaderpanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(ccsheaderlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ccsbackbtn)
                .addGap(12, 12, 12)
                .addComponent(ccsminimizebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ccsclosebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        ccsheaderpanelLayout.setVerticalGroup(
            ccsheaderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ccsheaderpanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(ccsheaderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ccsheaderlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ccsbackbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ccsclosebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ccsminimizebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        ccsfooterpanel.setBackground(new java.awt.Color(1, 51, 153));
        ccsfooterpanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(-20, 0, 0, 0));
        ccsfooterpanel.setPreferredSize(new java.awt.Dimension(741, 75));

        ccsfooterlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ccsfooterlbl.setForeground(new java.awt.Color(255, 255, 255));
        ccsfooterlbl.setText("Niño Jay Bueta, Jose Cresnald Cosico - 3IS2");

        javax.swing.GroupLayout ccsfooterpanelLayout = new javax.swing.GroupLayout(ccsfooterpanel);
        ccsfooterpanel.setLayout(ccsfooterpanelLayout);
        ccsfooterpanelLayout.setHorizontalGroup(
            ccsfooterpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ccsfooterpanelLayout.createSequentialGroup()
                .addGap(575, 575, 575)
                .addComponent(ccsfooterlbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ccsfooterpanelLayout.setVerticalGroup(
            ccsfooterpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ccsfooterpanelLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(ccsfooterlbl)
                .addGap(18, 18, 18))
        );

        ccspanel1.setBackground(new java.awt.Color(255, 255, 255));
        ccspanel1.setMinimumSize(new java.awt.Dimension(372, 277));
        ccspanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ccslbl1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ccslbl1.setForeground(new java.awt.Color(1, 51, 153));
        ccslbl1.setText("College Of Computer Studies");
        ccspanel1.add(ccslbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        ccslbl2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ccslbl2.setText("<html>The College of Computer Studies (CCS) provides quality education in the field of information technology, <br>\ncomputer science, and information systems. It aims to develop professionals with strong technical and<br> analytical skills \nthat meet the needs of the industry.<br></html>");
        ccspanel1.add(ccslbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        ccspanel1.add(ccsimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 350, 224));

        ccspanel2.setBackground(new java.awt.Color(255, 255, 255));

        ccslbl3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ccslbl3.setForeground(new java.awt.Color(1, 51, 153));
        ccslbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ccslbl3.setText("BSCS");
        ccslbl3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        ccslbl4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ccslbl4.setText("Bachelor of Science in Computer Science");

        javax.swing.GroupLayout ccspanel2Layout = new javax.swing.GroupLayout(ccspanel2);
        ccspanel2.setLayout(ccspanel2Layout);
        ccspanel2Layout.setHorizontalGroup(
            ccspanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ccspanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(ccslbl4)
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ccspanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ccslbl3)
                .addGap(181, 181, 181))
        );
        ccspanel2Layout.setVerticalGroup(
            ccspanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ccspanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(ccslbl3)
                .addGap(111, 111, 111)
                .addComponent(ccslbl4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ccspanel3.setBackground(new java.awt.Color(255, 255, 255));

        ccslbl5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ccslbl5.setForeground(new java.awt.Color(1, 51, 153));
        ccslbl5.setText("BSIT");

        ccslbl6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ccslbl6.setText("Bachelor of Science in Information Technology");

        javax.swing.GroupLayout ccspanel3Layout = new javax.swing.GroupLayout(ccspanel3);
        ccspanel3.setLayout(ccspanel3Layout);
        ccspanel3Layout.setHorizontalGroup(
            ccspanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ccspanel3Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(ccspanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ccspanel3Layout.createSequentialGroup()
                        .addComponent(ccslbl6)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ccspanel3Layout.createSequentialGroup()
                        .addComponent(ccslbl5)
                        .addGap(220, 220, 220))))
        );
        ccspanel3Layout.setVerticalGroup(
            ccspanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ccspanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(ccslbl5)
                .addGap(116, 116, 116)
                .addComponent(ccslbl6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ccspanel4.setBackground(new java.awt.Color(255, 255, 255));
        ccspanel4.setPreferredSize(new java.awt.Dimension(430, 365));

        ccslbl7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ccslbl7.setForeground(new java.awt.Color(1, 51, 153));
        ccslbl7.setText("BSIS");

        ccslbl8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ccslbl8.setText("Bachelor of Science in Information System");

        javax.swing.GroupLayout ccspanel4Layout = new javax.swing.GroupLayout(ccspanel4);
        ccspanel4.setLayout(ccspanel4Layout);
        ccspanel4Layout.setHorizontalGroup(
            ccspanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ccspanel4Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(ccspanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ccspanel4Layout.createSequentialGroup()
                        .addComponent(ccslbl7)
                        .addGap(184, 184, 184))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ccspanel4Layout.createSequentialGroup()
                        .addComponent(ccslbl8)
                        .addGap(66, 66, 66))))
        );
        ccspanel4Layout.setVerticalGroup(
            ccspanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ccspanel4Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(ccslbl7)
                .addGap(121, 121, 121)
                .addComponent(ccslbl8)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ccsbodypanelLayout = new javax.swing.GroupLayout(ccsbodypanel);
        ccsbodypanel.setLayout(ccsbodypanelLayout);
        ccsbodypanelLayout.setHorizontalGroup(
            ccsbodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ccsbodypanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(ccsbodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ccspanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1435, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ccsbodypanelLayout.createSequentialGroup()
                        .addComponent(ccspanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ccspanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(ccspanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addComponent(ccsheaderpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ccsfooterpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1524, Short.MAX_VALUE)
        );
        ccsbodypanelLayout.setVerticalGroup(
            ccsbodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ccsbodypanelLayout.createSequentialGroup()
                .addComponent(ccsheaderpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ccspanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ccsbodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ccspanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ccspanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ccspanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(ccsfooterpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ccsbodypanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ccsbodypanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ccsbackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccsbackbtnActionPerformed
        FrmMainMenu_Bueta_Cosico main = new FrmMainMenu_Bueta_Cosico();
        main.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_ccsbackbtnActionPerformed

    private void ccsminimizebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccsminimizebtnActionPerformed
        setState(JFrame.ICONIFIED);
        // TODO add your handling code here:
    }//GEN-LAST:event_ccsminimizebtnActionPerformed

    private void ccsclosebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccsclosebtnActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_ccsclosebtnActionPerformed
    
    private void addHover(JPanel panel) {
    panel.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseEntered(MouseEvent e) {
            panel.setBackground(ThemeManager.hoverColor); // temporary hover color
            panel.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }

        @Override
        public void mouseExited(MouseEvent e) {
            panel.setBackground(ThemeManager.bodyColor); // revert to current theme color
        }
     });
    }

    

    public class ShadowRoundedPanel extends JPanel {

    private int cornerRadius = 20;
    private int shadowSize = 8;

    public ShadowRoundedPanel(int radius) {
        this.cornerRadius = radius;
        setOpaque(false);
    }

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();

        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        // Shadow
        g2.setColor(new Color(0, 0, 0, 40)); // light shadow
        g2.fillRoundRect(
            shadowSize,
            shadowSize,
            getWidth() - shadowSize,
            getHeight() - shadowSize,
            cornerRadius,
            cornerRadius
        );

        // Main panel
        g2.setColor(getBackground());
        g2.fillRoundRect(
            0,
            0,
            getWidth() - shadowSize,
            getHeight() - shadowSize,
            cornerRadius,
            cornerRadius
        );

        g2.dispose();
        super.paintComponent(g);
       }
    }
    
    private void updateTheme() {
    // Panels
    ccsheaderpanel.setBackground(ThemeManager.headerColor);
    ccsbodypanel.setBackground(ThemeManager.bodyColor);
    ccsfooterpanel.setBackground(ThemeManager.footerColor);

    // Labels
    ccslbl1.setForeground(ThemeManager.textColor);
    ccslbl2.setForeground(ThemeManager.textColor);
    ccslbl3.setForeground(ThemeManager.textColor);
    ccslbl4.setForeground(ThemeManager.textColor);
    ccslbl5.setForeground(ThemeManager.textColor);
    ccslbl6.setForeground(ThemeManager.textColor);
    ccslbl7.setForeground(ThemeManager.textColor);
    ccslbl8.setForeground(ThemeManager.textColor);
    
    //Panels
    ccspanel1.setBackground(ThemeManager.bodyColor);
    ccspanel2.setBackground(ThemeManager.bodyColor);
    ccspanel3.setBackground(ThemeManager.bodyColor);
    ccspanel4.setBackground(ThemeManager.bodyColor);
    
    // Buttons
    ccsbackbtn.setForeground(ThemeManager.btnColor);
    ccsminimizebtn.setForeground(ThemeManager.btnColor);
    ccsclosebtn.setForeground(ThemeManager.btnColor);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmCCS_Bueta_Cosico().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ccsbackbtn;
    private javax.swing.JPanel ccsbodypanel;
    private javax.swing.JButton ccsclosebtn;
    private javax.swing.JLabel ccsfooterlbl;
    private javax.swing.JPanel ccsfooterpanel;
    private javax.swing.JLabel ccsheaderlbl;
    private javax.swing.JPanel ccsheaderpanel;
    private javax.swing.JLabel ccsimg;
    private javax.swing.JLabel ccslbl1;
    private javax.swing.JLabel ccslbl2;
    private javax.swing.JLabel ccslbl3;
    private javax.swing.JLabel ccslbl4;
    private javax.swing.JLabel ccslbl5;
    private javax.swing.JLabel ccslbl6;
    private javax.swing.JLabel ccslbl7;
    private javax.swing.JLabel ccslbl8;
    private javax.swing.JButton ccsminimizebtn;
    private javax.swing.JPanel ccspanel1;
    private javax.swing.JPanel ccspanel2;
    private javax.swing.JPanel ccspanel3;
    private javax.swing.JPanel ccspanel4;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
