/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bueta_cosico_lspunavigation;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import com.mycompany.bueta_cosico_lspunavigation.ThemeManager;
import java.awt.event.MouseEvent;

/**
 *
 * @author Shinozaki
 */
public class FrmCTE_Bueta_Cosico extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCTE_Bueta_Cosico.class.getName());

    /**
     * Creates new form FrmCTE_Bueta_Cosico
     */
    public FrmCTE_Bueta_Cosico() {
        this.setUndecorated(true);
        initComponents();
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/bueta_cosico_lspunavigation/images/cte.png"));
        Image img = icon.getImage().getScaledInstance(400, 300, Image.SCALE_SMOOTH);
        cteimg.setIcon(new ImageIcon(img));
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        ThemeManager.applyTheme(ThemeManager.currentTheme); // Apply current theme
        updateTheme(); 
        
        addHover(ctepanel1);
        addHover(ctepanel2);
        addHover(ctepanel3);
        addHover(ctepanel4);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ctebodypanel = new javax.swing.JPanel();
        cteheaderpanel = new javax.swing.JPanel();
        cteheaderlbl = new javax.swing.JLabel();
        ctebackbtn = new javax.swing.JButton();
        cteclosebtn = new javax.swing.JButton();
        cteminimizebtn = new javax.swing.JButton();
        ctefooterpanel = new javax.swing.JPanel();
        ctefooterlbl = new javax.swing.JLabel();
        ctepanel1 = new ShadowRoundedPanel(20);
        ctelbl1 = new javax.swing.JLabel();
        ctelbl2 = new javax.swing.JLabel();
        cteimg = new javax.swing.JLabel();
        ctepanel2 = new ShadowRoundedPanel(20);
        ctelbl3 = new javax.swing.JLabel();
        ctelbl4 = new javax.swing.JLabel();
        ctepanel3 = new ShadowRoundedPanel(20);
        ctelbl5 = new javax.swing.JLabel();
        ctelbl6 = new javax.swing.JLabel();
        ctepanel4 = new ShadowRoundedPanel(20);
        ctelbl7 = new javax.swing.JLabel();
        ctelbl8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cteheaderpanel.setBackground(new java.awt.Color(1, 51, 153));

        cteheaderlbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        cteheaderlbl.setForeground(new java.awt.Color(255, 255, 255));
        cteheaderlbl.setText("SOME COLLEGES IN LSPU - Bueta_Cosico");

        ctebackbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ctebackbtn.setForeground(new java.awt.Color(1, 51, 153));
        ctebackbtn.setText("BACK TO MAIN MENU");
        ctebackbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ctebackbtn.setFocusPainted(false);
        ctebackbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctebackbtnActionPerformed(evt);
            }
        });

        cteclosebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cteclosebtn.setForeground(new java.awt.Color(1, 51, 153));
        cteclosebtn.setText("✕");
        cteclosebtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cteclosebtn.setFocusPainted(false);
        cteclosebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cteclosebtnActionPerformed(evt);
            }
        });

        cteminimizebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cteminimizebtn.setForeground(new java.awt.Color(1, 51, 153));
        cteminimizebtn.setText("—");
        cteminimizebtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cteminimizebtn.setFocusPainted(false);
        cteminimizebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cteminimizebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cteheaderpanelLayout = new javax.swing.GroupLayout(cteheaderpanel);
        cteheaderpanel.setLayout(cteheaderpanelLayout);
        cteheaderpanelLayout.setHorizontalGroup(
            cteheaderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cteheaderpanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(cteheaderlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ctebackbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cteminimizebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cteclosebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        cteheaderpanelLayout.setVerticalGroup(
            cteheaderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cteheaderpanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(cteheaderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cteheaderlbl)
                    .addGroup(cteheaderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ctebackbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cteminimizebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cteclosebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        ctefooterpanel.setBackground(new java.awt.Color(1, 51, 153));

        ctefooterlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ctefooterlbl.setForeground(new java.awt.Color(255, 255, 255));
        ctefooterlbl.setText("Niño Jay Bueta_Jose Cresnald Cosico - 3IS2");

        javax.swing.GroupLayout ctefooterpanelLayout = new javax.swing.GroupLayout(ctefooterpanel);
        ctefooterpanel.setLayout(ctefooterpanelLayout);
        ctefooterpanelLayout.setHorizontalGroup(
            ctefooterpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ctefooterpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ctefooterlbl)
                .addGap(613, 613, 613))
        );
        ctefooterpanelLayout.setVerticalGroup(
            ctefooterpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ctefooterpanelLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(ctefooterlbl)
                .addGap(25, 25, 25))
        );

        ctepanel1.setBackground(new java.awt.Color(255, 255, 255));

        ctelbl1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ctelbl1.setForeground(new java.awt.Color(1, 51, 153));
        ctelbl1.setText("College of Teacher Education");

        ctelbl2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ctelbl2.setText("<html>The College of Teacher Education (CTE)\n               prepares future educators with a strong foundation in pedagogy,<br> curriculum design\n                and classroom management for various levels of education.</html>\n");

        javax.swing.GroupLayout ctepanel1Layout = new javax.swing.GroupLayout(ctepanel1);
        ctepanel1.setLayout(ctepanel1Layout);
        ctepanel1Layout.setHorizontalGroup(
            ctepanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ctepanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(ctepanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ctelbl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctelbl1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                .addComponent(cteimg, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        ctepanel1Layout.setVerticalGroup(
            ctepanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ctepanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(ctepanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cteimg, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ctepanel1Layout.createSequentialGroup()
                        .addComponent(ctelbl1)
                        .addGap(35, 35, 35)
                        .addComponent(ctelbl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        ctepanel2.setBackground(new java.awt.Color(255, 255, 255));
        ctepanel2.setPreferredSize(new java.awt.Dimension(475, 235));

        ctelbl3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ctelbl3.setForeground(new java.awt.Color(1, 51, 153));
        ctelbl3.setText("BSEd");

        ctelbl4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ctelbl4.setText("Bachelor of Secondary Education");

        javax.swing.GroupLayout ctepanel2Layout = new javax.swing.GroupLayout(ctepanel2);
        ctepanel2.setLayout(ctepanel2Layout);
        ctepanel2Layout.setHorizontalGroup(
            ctepanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ctepanel2Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(ctepanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ctepanel2Layout.createSequentialGroup()
                        .addComponent(ctelbl4)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ctepanel2Layout.createSequentialGroup()
                        .addComponent(ctelbl3)
                        .addGap(180, 180, 180))))
        );
        ctepanel2Layout.setVerticalGroup(
            ctepanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ctepanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(ctelbl3)
                .addGap(102, 102, 102)
                .addComponent(ctelbl4)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        ctepanel3.setBackground(new java.awt.Color(255, 255, 255));
        ctepanel3.setPreferredSize(new java.awt.Dimension(475, 235));

        ctelbl5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ctelbl5.setForeground(new java.awt.Color(1, 51, 153));
        ctelbl5.setText("BEEd");

        ctelbl6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ctelbl6.setText("Bachelor of Elementary Education");

        javax.swing.GroupLayout ctepanel3Layout = new javax.swing.GroupLayout(ctepanel3);
        ctepanel3.setLayout(ctepanel3Layout);
        ctepanel3Layout.setHorizontalGroup(
            ctepanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ctepanel3Layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(ctepanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ctepanel3Layout.createSequentialGroup()
                        .addComponent(ctelbl6)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ctepanel3Layout.createSequentialGroup()
                        .addComponent(ctelbl5)
                        .addGap(180, 180, 180))))
        );
        ctepanel3Layout.setVerticalGroup(
            ctepanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ctepanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(ctelbl5)
                .addGap(102, 102, 102)
                .addComponent(ctelbl6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ctepanel4.setBackground(new java.awt.Color(255, 255, 255));
        ctepanel4.setPreferredSize(new java.awt.Dimension(440, 198));

        ctelbl7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ctelbl7.setForeground(new java.awt.Color(1, 51, 153));
        ctelbl7.setText("BTLEd");

        ctelbl8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ctelbl8.setText("Bachelor of Technology and Livelihood Eduction");

        javax.swing.GroupLayout ctepanel4Layout = new javax.swing.GroupLayout(ctepanel4);
        ctepanel4.setLayout(ctepanel4Layout);
        ctepanel4Layout.setHorizontalGroup(
            ctepanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ctepanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ctelbl7)
                .addGap(175, 175, 175))
            .addGroup(ctepanel4Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(ctelbl8)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        ctepanel4Layout.setVerticalGroup(
            ctepanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ctepanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(ctelbl7)
                .addGap(108, 108, 108)
                .addComponent(ctelbl8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ctebodypanelLayout = new javax.swing.GroupLayout(ctebodypanel);
        ctebodypanel.setLayout(ctebodypanelLayout);
        ctebodypanelLayout.setHorizontalGroup(
            ctebodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cteheaderpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ctebodypanelLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(ctebodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ctebodypanelLayout.createSequentialGroup()
                        .addComponent(ctepanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addComponent(ctepanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(ctepanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ctepanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
            .addComponent(ctefooterpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ctebodypanelLayout.setVerticalGroup(
            ctebodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ctebodypanelLayout.createSequentialGroup()
                .addComponent(cteheaderpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(ctepanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(ctebodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ctepanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(ctepanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(ctepanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(ctefooterpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ctebodypanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ctebodypanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ctebackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctebackbtnActionPerformed
        FrmMainMenu_Bueta_Cosico main = new FrmMainMenu_Bueta_Cosico();
        main.setVisible(true);
        this.dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_ctebackbtnActionPerformed

    private void cteminimizebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cteminimizebtnActionPerformed
       setState(JFrame.ICONIFIED); // TODO add your handling code here:
    }//GEN-LAST:event_cteminimizebtnActionPerformed

    private void cteclosebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cteclosebtnActionPerformed
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_cteclosebtnActionPerformed
    
   
    private void addHover(JPanel panel) {
    panel.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseEntered(MouseEvent e) {
            panel.setBackground(ThemeManager.hoverColor); // temporary hover color
            panel.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }

        @Override
        public void mouseExited(MouseEvent e) {
            panel.setBackground(ThemeManager.bodyColor); // revert to current theme color
        }
     });
    }
    

    public class ShadowRoundedPanel extends JPanel {

    private int cornerRadius = 20;
    private int shadowSize = 8;

    public ShadowRoundedPanel(int radius) {
        this.cornerRadius = radius;
        setOpaque(false);
    }

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();

        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        // Shadow
        g2.setColor(new Color(0, 0, 0, 40)); // light shadow
        g2.fillRoundRect(
            shadowSize,
            shadowSize,
            getWidth() - shadowSize,
            getHeight() - shadowSize,
            cornerRadius,
            cornerRadius
        );

        // Main panel
        g2.setColor(getBackground());
        g2.fillRoundRect(
            0,
            0,
            getWidth() - shadowSize,
            getHeight() - shadowSize,
            cornerRadius,
            cornerRadius
        );

        g2.dispose();
        super.paintComponent(g);
       }
    }
    
    private void updateTheme() {
    // Panels
    cteheaderpanel.setBackground(ThemeManager.headerColor);
    ctebodypanel.setBackground(ThemeManager.bodyColor);
    ctefooterpanel.setBackground(ThemeManager.footerColor);

    // Labels
    ctelbl1.setForeground(ThemeManager.textColor);
    ctelbl2.setForeground(ThemeManager.textColor);
    ctelbl3.setForeground(ThemeManager.textColor);
    ctelbl4.setForeground(ThemeManager.textColor);
    ctelbl5.setForeground(ThemeManager.textColor);
    ctelbl6.setForeground(ThemeManager.textColor);
    ctelbl7.setForeground(ThemeManager.textColor);
    ctelbl8.setForeground(ThemeManager.textColor);
    
    //Panels
    ctepanel1.setBackground(ThemeManager.bodyColor);
    ctepanel2.setBackground(ThemeManager.bodyColor);
    ctepanel3.setBackground(ThemeManager.bodyColor);
    ctepanel4.setBackground(ThemeManager.bodyColor);
    
    // Buttons
    ctebackbtn.setForeground(ThemeManager.btnColor);
    cteminimizebtn.setForeground(ThemeManager.btnColor);
    cteclosebtn.setForeground(ThemeManager.btnColor);
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmCTE_Bueta_Cosico().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ctebackbtn;
    private javax.swing.JPanel ctebodypanel;
    private javax.swing.JButton cteclosebtn;
    private javax.swing.JLabel ctefooterlbl;
    private javax.swing.JPanel ctefooterpanel;
    private javax.swing.JLabel cteheaderlbl;
    private javax.swing.JPanel cteheaderpanel;
    private javax.swing.JLabel cteimg;
    private javax.swing.JLabel ctelbl1;
    private javax.swing.JLabel ctelbl2;
    private javax.swing.JLabel ctelbl3;
    private javax.swing.JLabel ctelbl4;
    private javax.swing.JLabel ctelbl5;
    private javax.swing.JLabel ctelbl6;
    private javax.swing.JLabel ctelbl7;
    private javax.swing.JLabel ctelbl8;
    private javax.swing.JButton cteminimizebtn;
    private javax.swing.JPanel ctepanel1;
    private javax.swing.JPanel ctepanel2;
    private javax.swing.JPanel ctepanel3;
    private javax.swing.JPanel ctepanel4;
    // End of variables declaration//GEN-END:variables
}
