/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bueta_cosico_lspunavigation;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.event.MouseEvent;

/**
 *
 * @author Shinozaki
 */
public class FrmCOE_Bueta_Cosico extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCOE_Bueta_Cosico.class.getName());

    /**
     * Creates new form FrmCOE_Bueta_Cosico
     */
    public FrmCOE_Bueta_Cosico() {
        this.setUndecorated(true);
        initComponents();
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/bueta_cosico_lspunavigation/images/coe.png"));
        Image img = icon.getImage().getScaledInstance(400, 300, Image.SCALE_SMOOTH);
        coeimg.setIcon(new ImageIcon(img));
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        ThemeManager.applyTheme(ThemeManager.currentTheme); // Apply current theme
        updateTheme(); 
        
        
        addHover(coepanel1);
        addHover(coepanel2);
        addHover(coepanel3);
        addHover(coepanel4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        coebodypanel = new javax.swing.JPanel();
        coepanel1 = new ShadowRoundedPanel(20);
        coelbl1 = new javax.swing.JLabel();
        coelbl2 = new javax.swing.JLabel();
        coeimg = new javax.swing.JLabel();
        coepanel2 = new ShadowRoundedPanel(20);
        coelbl3 = new javax.swing.JLabel();
        coelbl4 = new javax.swing.JLabel();
        coepanel3 = new ShadowRoundedPanel(20);
        coelbl5 = new javax.swing.JLabel();
        coelbl6 = new javax.swing.JLabel();
        coefooterpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        coeheaderpanel = new javax.swing.JPanel();
        coebackbtn = new javax.swing.JButton();
        coeheaderlbl = new javax.swing.JLabel();
        coeminimizebtn = new javax.swing.JButton();
        coeclosebtn = new javax.swing.JButton();
        coepanel4 = new ShadowRoundedPanel(20);
        coelbl7 = new javax.swing.JLabel();
        coelbl8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        coepanel1.setBackground(new java.awt.Color(255, 255, 255));

        coelbl1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        coelbl1.setForeground(new java.awt.Color(1, 51, 153));
        coelbl1.setText("College of Engineering");

        coelbl2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        coelbl2.setText("<html>The College of Engineering (COE) is dedicated to producing highly skilled engineers  who are equipped with technical<br> knowledge and innovative thinking. The college fosters excellence in civil, electrical, and software engineering  with<br> emphasis on practical and sustainable solutions to real-world problems.</html>");

        javax.swing.GroupLayout coepanel1Layout = new javax.swing.GroupLayout(coepanel1);
        coepanel1.setLayout(coepanel1Layout);
        coepanel1Layout.setHorizontalGroup(
            coepanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coepanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(coepanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coelbl1)
                    .addComponent(coelbl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(coeimg, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        coepanel1Layout.setVerticalGroup(
            coepanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coepanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(coepanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coeimg, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(coepanel1Layout.createSequentialGroup()
                        .addComponent(coelbl1)
                        .addGap(18, 18, 18)
                        .addComponent(coelbl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        coepanel2.setBackground(new java.awt.Color(255, 255, 255));

        coelbl3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        coelbl3.setForeground(new java.awt.Color(1, 51, 153));
        coelbl3.setText("BSCE");

        coelbl4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        coelbl4.setText("Bachelor of Science in Civil Engineering");

        javax.swing.GroupLayout coepanel2Layout = new javax.swing.GroupLayout(coepanel2);
        coepanel2.setLayout(coepanel2Layout);
        coepanel2Layout.setHorizontalGroup(
            coepanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coepanel2Layout.createSequentialGroup()
                .addGroup(coepanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(coepanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(coelbl4))
                    .addGroup(coepanel2Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(coelbl3)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        coepanel2Layout.setVerticalGroup(
            coepanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coepanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(coelbl3)
                .addGap(114, 114, 114)
                .addComponent(coelbl4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        coepanel3.setBackground(new java.awt.Color(255, 255, 255));
        coepanel3.setPreferredSize(new java.awt.Dimension(430, 378));

        coelbl5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        coelbl5.setForeground(new java.awt.Color(1, 51, 153));
        coelbl5.setText("BSEE");

        coelbl6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        coelbl6.setText("Bachelor of Science in Electrical Engineering");

        javax.swing.GroupLayout coepanel3Layout = new javax.swing.GroupLayout(coepanel3);
        coepanel3.setLayout(coepanel3Layout);
        coepanel3Layout.setHorizontalGroup(
            coepanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coepanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(coelbl5)
                .addGap(180, 180, 180))
            .addGroup(coepanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(coelbl6)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        coepanel3Layout.setVerticalGroup(
            coepanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coepanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(coelbl5)
                .addGap(114, 114, 114)
                .addComponent(coelbl6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        coefooterpanel.setBackground(new java.awt.Color(1, 51, 153));
        coefooterpanel.setPreferredSize(new java.awt.Dimension(741, 75));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Niño Jay Bueta, Jose Cresnald Cosico - 3IS2");

        javax.swing.GroupLayout coefooterpanelLayout = new javax.swing.GroupLayout(coefooterpanel);
        coefooterpanel.setLayout(coefooterpanelLayout);
        coefooterpanelLayout.setHorizontalGroup(
            coefooterpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coefooterpanelLayout.createSequentialGroup()
                .addGap(611, 611, 611)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        coefooterpanelLayout.setVerticalGroup(
            coefooterpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coefooterpanelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(24, 24, 24))
        );

        coeheaderpanel.setBackground(new java.awt.Color(1, 51, 153));
        coeheaderpanel.setPreferredSize(new java.awt.Dimension(741, 75));

        coebackbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        coebackbtn.setForeground(new java.awt.Color(1, 51, 153));
        coebackbtn.setText("BACK TO MAIN MENU");
        coebackbtn.setFocusPainted(false);
        coebackbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coebackbtnActionPerformed(evt);
            }
        });

        coeheaderlbl.setBackground(new java.awt.Color(255, 255, 255));
        coeheaderlbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        coeheaderlbl.setForeground(new java.awt.Color(255, 255, 255));
        coeheaderlbl.setText("SOME COLLEGES IN LSPU - Bueta_Cosico");

        coeminimizebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        coeminimizebtn.setForeground(new java.awt.Color(1, 51, 153));
        coeminimizebtn.setText("—");
        coeminimizebtn.setFocusPainted(false);
        coeminimizebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coeminimizebtnActionPerformed(evt);
            }
        });

        coeclosebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        coeclosebtn.setForeground(new java.awt.Color(1, 51, 153));
        coeclosebtn.setText("✕");
        coeclosebtn.setFocusPainted(false);
        coeclosebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coeclosebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout coeheaderpanelLayout = new javax.swing.GroupLayout(coeheaderpanel);
        coeheaderpanel.setLayout(coeheaderpanelLayout);
        coeheaderpanelLayout.setHorizontalGroup(
            coeheaderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coeheaderpanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(coeheaderlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(coebackbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(coeminimizebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(coeclosebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        coeheaderpanelLayout.setVerticalGroup(
            coeheaderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coeheaderpanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(coeheaderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coeheaderlbl)
                    .addGroup(coeheaderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(coeminimizebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(coebackbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(coeclosebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        coepanel4.setBackground(new java.awt.Color(255, 255, 255));
        coepanel4.setPreferredSize(new java.awt.Dimension(430, 378));

        coelbl7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        coelbl7.setForeground(new java.awt.Color(1, 51, 153));
        coelbl7.setText("BSSE");

        coelbl8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        coelbl8.setText("Bachelor of Science in Software Engineering");

        javax.swing.GroupLayout coepanel4Layout = new javax.swing.GroupLayout(coepanel4);
        coepanel4.setLayout(coepanel4Layout);
        coepanel4Layout.setHorizontalGroup(
            coepanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coepanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(coelbl7)
                .addGap(185, 185, 185))
            .addGroup(coepanel4Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(coelbl8)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        coepanel4Layout.setVerticalGroup(
            coepanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coepanel4Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(coelbl7)
                .addGap(110, 110, 110)
                .addComponent(coelbl8)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout coebodypanelLayout = new javax.swing.GroupLayout(coebodypanel);
        coebodypanel.setLayout(coebodypanelLayout);
        coebodypanelLayout.setHorizontalGroup(
            coebodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(coeheaderpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1589, Short.MAX_VALUE)
            .addComponent(coefooterpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1589, Short.MAX_VALUE)
            .addGroup(coebodypanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(coebodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(coepanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(coebodypanelLayout.createSequentialGroup()
                        .addComponent(coepanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(coepanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(coepanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74))
        );
        coebodypanelLayout.setVerticalGroup(
            coebodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coebodypanelLayout.createSequentialGroup()
                .addComponent(coeheaderpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(coepanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(coebodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(coepanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                    .addComponent(coepanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                    .addComponent(coepanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(coefooterpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(coebodypanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(coebodypanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void coebackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coebackbtnActionPerformed
        FrmMainMenu_Bueta_Cosico main = new FrmMainMenu_Bueta_Cosico();
        main.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_coebackbtnActionPerformed

    private void coeminimizebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coeminimizebtnActionPerformed
        setState(JFrame.ICONIFIED);   // TODO add your handling code here:
    }//GEN-LAST:event_coeminimizebtnActionPerformed

    private void coeclosebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coeclosebtnActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_coeclosebtnActionPerformed
    
    

    public class ShadowRoundedPanel extends JPanel {

    private int cornerRadius = 20;
    private int shadowSize = 8;

    public ShadowRoundedPanel(int radius) {
        this.cornerRadius = radius;
        setOpaque(false);
    }

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();

        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        // Shadow
        g2.setColor(new Color(0, 0, 0, 40)); // light shadow
        g2.fillRoundRect(
            shadowSize,
            shadowSize,
            getWidth() - shadowSize,
            getHeight() - shadowSize,
            cornerRadius,
            cornerRadius
        );

        // Main panel
        g2.setColor(getBackground());
        g2.fillRoundRect(
            0,
            0,
            getWidth() - shadowSize,
            getHeight() - shadowSize,
            cornerRadius,
            cornerRadius
        );

        g2.dispose();
        super.paintComponent(g);
       }
    }
    
    private void addHover(JPanel panel) {
    panel.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseEntered(MouseEvent e) {
            panel.setBackground(ThemeManager.hoverColor); // temporary hover color
            panel.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }

        @Override
        public void mouseExited(MouseEvent e) {
            panel.setBackground(ThemeManager.bodyColor); // revert to current theme color
        }
     });
    }
    
    private void updateTheme() {
    // Panels
    coeheaderpanel.setBackground(ThemeManager.headerColor);
    coebodypanel.setBackground(ThemeManager.bodyColor);
    coefooterpanel.setBackground(ThemeManager.footerColor);

    // Labels
    coelbl1.setForeground(ThemeManager.textColor);
    coelbl2.setForeground(ThemeManager.textColor);
    coelbl3.setForeground(ThemeManager.textColor);
    coelbl4.setForeground(ThemeManager.textColor);
    coelbl5.setForeground(ThemeManager.textColor);
    coelbl6.setForeground(ThemeManager.textColor);
    coelbl7.setForeground(ThemeManager.textColor);
    coelbl8.setForeground(ThemeManager.textColor);
    
    //Panels
    coepanel1.setBackground(ThemeManager.bodyColor);
    coepanel2.setBackground(ThemeManager.bodyColor);
    coepanel3.setBackground(ThemeManager.bodyColor);
    coepanel4.setBackground(ThemeManager.bodyColor);
    
    // Buttons
    coebackbtn.setForeground(ThemeManager.btnColor);
    coeminimizebtn.setForeground(ThemeManager.btnColor);
    coeclosebtn.setForeground(ThemeManager.btnColor);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmCOE_Bueta_Cosico().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton coebackbtn;
    private javax.swing.JPanel coebodypanel;
    private javax.swing.JButton coeclosebtn;
    private javax.swing.JPanel coefooterpanel;
    private javax.swing.JLabel coeheaderlbl;
    private javax.swing.JPanel coeheaderpanel;
    private javax.swing.JLabel coeimg;
    private javax.swing.JLabel coelbl1;
    private javax.swing.JLabel coelbl2;
    private javax.swing.JLabel coelbl3;
    private javax.swing.JLabel coelbl4;
    private javax.swing.JLabel coelbl5;
    private javax.swing.JLabel coelbl6;
    private javax.swing.JLabel coelbl7;
    private javax.swing.JLabel coelbl8;
    private javax.swing.JButton coeminimizebtn;
    private javax.swing.JPanel coepanel1;
    private javax.swing.JPanel coepanel2;
    private javax.swing.JPanel coepanel3;
    private javax.swing.JPanel coepanel4;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
