/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bueta_cosico_lspunavigation;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.event.MouseEvent;

/**
 *
 * @author Shinozaki
 */
public class FrmCBAA_Bueta_Cosico extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCBAA_Bueta_Cosico.class.getName());

    /**
     * Creates new form FrmCBAA_Bueta_Cosico
     */
    public FrmCBAA_Bueta_Cosico() {
        this.setUndecorated(true);
        initComponents();
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/bueta_cosico_lspunavigation/images/cbaa.png"));
        Image img = icon.getImage().getScaledInstance(400, 300, Image.SCALE_SMOOTH);
        cbaaimg.setIcon(new ImageIcon(img));
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        ThemeManager.applyTheme(ThemeManager.currentTheme); // Apply current theme
        updateTheme();
        
        addHover(cbaapanel1);
        addHover(cbaapanel2);
        addHover(cbaapanel3);
        addHover(cbaapanel4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbaabodypanel = new javax.swing.JPanel();
        cbaaheaderpanel = new javax.swing.JPanel();
        cbaaheaderlbl = new javax.swing.JLabel();
        cbaabackbtn = new javax.swing.JButton();
        cbaaclosebtn = new javax.swing.JButton();
        cbaaminimizebtn = new javax.swing.JButton();
        cbaapanel1 = new ShadowRoundedPanel(20);
        cbaalbl1 = new javax.swing.JLabel();
        cbaalbl2 = new javax.swing.JLabel();
        cbaaimg = new javax.swing.JLabel();
        cbaafooterpanel = new javax.swing.JPanel();
        cbaafooterlbl = new javax.swing.JLabel();
        cbaapanel2 = new ShadowRoundedPanel(20);
        cbaalbl3 = new javax.swing.JLabel();
        cbaalbl4 = new javax.swing.JLabel();
        cbaapanel3 = new ShadowRoundedPanel(20);
        cbaalbl5 = new javax.swing.JLabel();
        cbaalbl6 = new javax.swing.JLabel();
        cbaapanel4 = new ShadowRoundedPanel(20);
        cbaalbl7 = new javax.swing.JLabel();
        cbaalbl8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbaaheaderpanel.setBackground(new java.awt.Color(1, 51, 153));
        cbaaheaderpanel.setPreferredSize(new java.awt.Dimension(741, 75));

        cbaaheaderlbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        cbaaheaderlbl.setForeground(new java.awt.Color(255, 255, 255));
        cbaaheaderlbl.setText("SOME COLLEGES IN LSPU - Bueta_Cosico");

        cbaabackbtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cbaabackbtn.setForeground(new java.awt.Color(1, 51, 153));
        cbaabackbtn.setText("BACK TO MAIN MENU");
        cbaabackbtn.setFocusPainted(false);
        cbaabackbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbaabackbtnActionPerformed(evt);
            }
        });

        cbaaclosebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbaaclosebtn.setForeground(new java.awt.Color(1, 51, 153));
        cbaaclosebtn.setText("✕");
        cbaaclosebtn.setFocusPainted(false);
        cbaaclosebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbaaclosebtnActionPerformed(evt);
            }
        });

        cbaaminimizebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbaaminimizebtn.setForeground(new java.awt.Color(1, 51, 153));
        cbaaminimizebtn.setText("—");
        cbaaminimizebtn.setFocusPainted(false);
        cbaaminimizebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbaaminimizebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cbaaheaderpanelLayout = new javax.swing.GroupLayout(cbaaheaderpanel);
        cbaaheaderpanel.setLayout(cbaaheaderpanelLayout);
        cbaaheaderpanelLayout.setHorizontalGroup(
            cbaaheaderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cbaaheaderpanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(cbaaheaderlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbaabackbtn)
                .addGap(18, 18, 18)
                .addComponent(cbaaminimizebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbaaclosebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        cbaaheaderpanelLayout.setVerticalGroup(
            cbaaheaderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cbaaheaderpanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(cbaaheaderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbaaheaderlbl)
                    .addGroup(cbaaheaderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbaabackbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbaaclosebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbaaminimizebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        cbaapanel1.setBackground(new java.awt.Color(255, 255, 255));

        cbaalbl1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cbaalbl1.setForeground(new java.awt.Color(1, 51, 153));
        cbaalbl1.setText("College of Business Administration and Accountancy");

        cbaalbl2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbaalbl2.setText("<html>The College of Business Administration and Accountancy (CBAA) \n                equips students with skills in business management,\n\t<br> marketing, and financial analysis,\n                preparing them for leadership roles in various industries.</html>");

        javax.swing.GroupLayout cbaapanel1Layout = new javax.swing.GroupLayout(cbaapanel1);
        cbaapanel1.setLayout(cbaapanel1Layout);
        cbaapanel1Layout.setHorizontalGroup(
            cbaapanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cbaapanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(cbaapanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbaalbl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbaalbl1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbaaimg, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        cbaapanel1Layout.setVerticalGroup(
            cbaapanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cbaapanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(cbaapanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbaaimg, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cbaapanel1Layout.createSequentialGroup()
                        .addComponent(cbaalbl1)
                        .addGap(18, 18, 18)
                        .addComponent(cbaalbl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        cbaafooterpanel.setBackground(new java.awt.Color(1, 51, 153));
        cbaafooterpanel.setPreferredSize(new java.awt.Dimension(741, 75));

        cbaafooterlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbaafooterlbl.setForeground(new java.awt.Color(255, 255, 255));
        cbaafooterlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cbaafooterlbl.setText("Niño Jay Bueta, Jose Cresnald Cosico - 3IS2");

        javax.swing.GroupLayout cbaafooterpanelLayout = new javax.swing.GroupLayout(cbaafooterpanel);
        cbaafooterpanel.setLayout(cbaafooterpanelLayout);
        cbaafooterpanelLayout.setHorizontalGroup(
            cbaafooterpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cbaafooterpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbaafooterlbl)
                .addGap(587, 587, 587))
        );
        cbaafooterpanelLayout.setVerticalGroup(
            cbaafooterpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cbaafooterpanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(cbaafooterlbl)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        cbaapanel2.setBackground(new java.awt.Color(255, 255, 255));
        cbaapanel2.setPreferredSize(new java.awt.Dimension(430, 365));

        cbaalbl3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cbaalbl3.setForeground(new java.awt.Color(1, 51, 153));
        cbaalbl3.setText("BSBA");

        cbaalbl4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbaalbl4.setText("Bachelor of Science in Business Administration");

        javax.swing.GroupLayout cbaapanel2Layout = new javax.swing.GroupLayout(cbaapanel2);
        cbaapanel2.setLayout(cbaapanel2Layout);
        cbaapanel2Layout.setHorizontalGroup(
            cbaapanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cbaapanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbaalbl3)
                .addGap(161, 161, 161))
            .addGroup(cbaapanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(cbaalbl4)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        cbaapanel2Layout.setVerticalGroup(
            cbaapanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cbaapanel2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(cbaalbl3)
                .addGap(101, 101, 101)
                .addComponent(cbaalbl4)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        cbaapanel3.setBackground(new java.awt.Color(255, 255, 255));
        cbaapanel3.setPreferredSize(new java.awt.Dimension(430, 365));

        cbaalbl5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cbaalbl5.setForeground(new java.awt.Color(1, 51, 153));
        cbaalbl5.setText("BSA");

        cbaalbl6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbaalbl6.setText("Bachelor of Science in Accountancy");

        javax.swing.GroupLayout cbaapanel3Layout = new javax.swing.GroupLayout(cbaapanel3);
        cbaapanel3.setLayout(cbaapanel3Layout);
        cbaapanel3Layout.setHorizontalGroup(
            cbaapanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cbaapanel3Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(cbaalbl5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cbaapanel3Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(cbaalbl6)
                .addGap(62, 62, 62))
        );
        cbaapanel3Layout.setVerticalGroup(
            cbaapanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cbaapanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(cbaalbl5)
                .addGap(109, 109, 109)
                .addComponent(cbaalbl6)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        cbaapanel4.setBackground(new java.awt.Color(255, 255, 255));
        cbaapanel4.setPreferredSize(new java.awt.Dimension(430, 365));

        cbaalbl7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cbaalbl7.setForeground(new java.awt.Color(1, 51, 153));
        cbaalbl7.setText("BSMA");

        cbaalbl8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbaalbl8.setText("Bachelor of Science in Management in Accounting");

        javax.swing.GroupLayout cbaapanel4Layout = new javax.swing.GroupLayout(cbaapanel4);
        cbaapanel4.setLayout(cbaapanel4Layout);
        cbaapanel4Layout.setHorizontalGroup(
            cbaapanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cbaapanel4Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(cbaapanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cbaapanel4Layout.createSequentialGroup()
                        .addComponent(cbaalbl7)
                        .addGap(150, 150, 150))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cbaapanel4Layout.createSequentialGroup()
                        .addComponent(cbaalbl8)
                        .addGap(16, 16, 16))))
        );
        cbaapanel4Layout.setVerticalGroup(
            cbaapanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cbaapanel4Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(cbaalbl7)
                .addGap(115, 115, 115)
                .addComponent(cbaalbl8)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cbaabodypanelLayout = new javax.swing.GroupLayout(cbaabodypanel);
        cbaabodypanel.setLayout(cbaabodypanelLayout);
        cbaabodypanelLayout.setHorizontalGroup(
            cbaabodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbaaheaderpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1547, Short.MAX_VALUE)
            .addComponent(cbaafooterpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1547, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cbaabodypanelLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(cbaabodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cbaapanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(cbaabodypanelLayout.createSequentialGroup()
                        .addComponent(cbaapanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156)
                        .addComponent(cbaapanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(cbaapanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(82, 82, 82))
        );
        cbaabodypanelLayout.setVerticalGroup(
            cbaabodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cbaabodypanelLayout.createSequentialGroup()
                .addComponent(cbaaheaderpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(cbaapanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(cbaabodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbaapanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbaapanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbaapanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(cbaafooterpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbaabodypanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbaabodypanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbaabackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbaabackbtnActionPerformed
            FrmMainMenu_Bueta_Cosico main = new FrmMainMenu_Bueta_Cosico();
            main.setVisible(true);
            this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_cbaabackbtnActionPerformed

    private void cbaaminimizebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbaaminimizebtnActionPerformed
       setState(JFrame.ICONIFIED);// TODO add your handling code here:
    }//GEN-LAST:event_cbaaminimizebtnActionPerformed

    private void cbaaclosebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbaaclosebtnActionPerformed
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_cbaaclosebtnActionPerformed
    
    private void addHover(JPanel panel) {
    panel.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseEntered(MouseEvent e) {
            panel.setBackground(ThemeManager.hoverColor); // temporary hover color
            panel.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }

        @Override
        public void mouseExited(MouseEvent e) {
            panel.setBackground(ThemeManager.bodyColor); // revert to current theme color
        }
     });
    }
    

    public class ShadowRoundedPanel extends JPanel {

    private int cornerRadius = 20;
    private int shadowSize = 8;

    public ShadowRoundedPanel(int radius) {
        this.cornerRadius = radius;
        setOpaque(false);
    }

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();

        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        // Shadow
        g2.setColor(new Color(0, 0, 0, 40)); // light shadow
        g2.fillRoundRect(
            shadowSize,
            shadowSize,
            getWidth() - shadowSize,
            getHeight() - shadowSize,
            cornerRadius,
            cornerRadius
        );

        // Main panel
        g2.setColor(getBackground());
        g2.fillRoundRect(
            0,
            0,
            getWidth() - shadowSize,
            getHeight() - shadowSize,
            cornerRadius,
            cornerRadius
        );

        g2.dispose();
        super.paintComponent(g);
       }
    }
    
    private void updateTheme() {
    // Panels
    cbaaheaderpanel.setBackground(ThemeManager.headerColor);
    cbaabodypanel.setBackground(ThemeManager.bodyColor);
    cbaafooterpanel.setBackground(ThemeManager.footerColor);

    // Labels
    cbaalbl1.setForeground(ThemeManager.textColor);
    cbaalbl2.setForeground(ThemeManager.textColor);
    cbaalbl3.setForeground(ThemeManager.textColor);
    cbaalbl4.setForeground(ThemeManager.textColor);
    cbaalbl5.setForeground(ThemeManager.textColor);
    cbaalbl6.setForeground(ThemeManager.textColor);
    cbaalbl7.setForeground(ThemeManager.textColor);
    cbaalbl8.setForeground(ThemeManager.textColor);
    
    //Panels
    cbaapanel1.setBackground(ThemeManager.bodyColor);
    cbaapanel2.setBackground(ThemeManager.bodyColor);
    cbaapanel3.setBackground(ThemeManager.bodyColor);
    cbaapanel4.setBackground(ThemeManager.bodyColor);
    
    // Buttons
    cbaabackbtn.setForeground(ThemeManager.btnColor);
    cbaaminimizebtn.setForeground(ThemeManager.btnColor);
    cbaaclosebtn.setForeground(ThemeManager.btnColor);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmCBAA_Bueta_Cosico().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cbaabackbtn;
    private javax.swing.JPanel cbaabodypanel;
    private javax.swing.JButton cbaaclosebtn;
    private javax.swing.JLabel cbaafooterlbl;
    private javax.swing.JPanel cbaafooterpanel;
    private javax.swing.JLabel cbaaheaderlbl;
    private javax.swing.JPanel cbaaheaderpanel;
    private javax.swing.JLabel cbaaimg;
    private javax.swing.JLabel cbaalbl1;
    private javax.swing.JLabel cbaalbl2;
    private javax.swing.JLabel cbaalbl3;
    private javax.swing.JLabel cbaalbl4;
    private javax.swing.JLabel cbaalbl5;
    private javax.swing.JLabel cbaalbl6;
    private javax.swing.JLabel cbaalbl7;
    private javax.swing.JLabel cbaalbl8;
    private javax.swing.JButton cbaaminimizebtn;
    private javax.swing.JPanel cbaapanel1;
    private javax.swing.JPanel cbaapanel2;
    private javax.swing.JPanel cbaapanel3;
    private javax.swing.JPanel cbaapanel4;
    // End of variables declaration//GEN-END:variables
}
