/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bueta_cosico_lspunavigation;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.event.MouseEvent;
/**
 *
 * @author Shinozaki
 */
public class FrmCIT_Bueta_Cosico extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCIT_Bueta_Cosico.class.getName());

    /**
     * Creates new form FrmCIT_Bueta_Cosico
     */
    public FrmCIT_Bueta_Cosico() {
        this.setUndecorated(true);
        initComponents();
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/bueta_cosico_lspunavigation/images/cit.png"));
        Image img = icon.getImage().getScaledInstance(400, 300, Image.SCALE_SMOOTH);
        citimg.setIcon(new ImageIcon(img));
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        ThemeManager.applyTheme(ThemeManager.currentTheme); // Apply current theme
        updateTheme();
        
        addHover(citpanel1);
        addHover(citpanel2);
        addHover(citpanel3);
        addHover(citpanel4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        citbodypanel = new javax.swing.JPanel();
        citheaderpanel = new javax.swing.JPanel();
        citheaderlbl = new javax.swing.JLabel();
        citbackbtn = new javax.swing.JButton();
        citclosebtn = new javax.swing.JButton();
        citminimizebtn = new javax.swing.JButton();
        citfooterpanel = new javax.swing.JPanel();
        citfooterlbl = new javax.swing.JLabel();
        citpanel1 = new ShadowRoundedPanel(20);
        citimg = new javax.swing.JLabel();
        citlbl1 = new javax.swing.JLabel();
        citlbl2 = new javax.swing.JLabel();
        citpanel2 = new ShadowRoundedPanel(20);
        citlbl3 = new javax.swing.JLabel();
        citlbl4 = new javax.swing.JLabel();
        citpanel3 = new ShadowRoundedPanel(20);
        citlbl5 = new javax.swing.JLabel();
        citlbl6 = new javax.swing.JLabel();
        citpanel4 = new ShadowRoundedPanel(20);
        citlbl7 = new javax.swing.JLabel();
        citlbl8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        citheaderpanel.setBackground(new java.awt.Color(1, 51, 153));
        citheaderpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        citheaderlbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        citheaderlbl.setForeground(new java.awt.Color(255, 255, 255));
        citheaderlbl.setText("SOME COLLEGES IN LSPU - Bueta_Cosico");
        citheaderpanel.add(citheaderlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        citbackbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        citbackbtn.setForeground(new java.awt.Color(1, 51, 153));
        citbackbtn.setText("BACK TO MAIN MENU");
        citbackbtn.setFocusPainted(false);
        citbackbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citbackbtnActionPerformed(evt);
            }
        });
        citheaderpanel.add(citbackbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 20, -1, 40));

        citclosebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        citclosebtn.setForeground(new java.awt.Color(1, 51, 153));
        citclosebtn.setText("✕");
        citclosebtn.setFocusPainted(false);
        citclosebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citclosebtnActionPerformed(evt);
            }
        });
        citheaderpanel.add(citclosebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 20, 50, 40));

        citminimizebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        citminimizebtn.setForeground(new java.awt.Color(1, 51, 153));
        citminimizebtn.setText("—");
        citminimizebtn.setFocusPainted(false);
        citminimizebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citminimizebtnActionPerformed(evt);
            }
        });
        citheaderpanel.add(citminimizebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 20, 50, 40));

        citfooterpanel.setBackground(new java.awt.Color(1, 51, 153));

        citfooterlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        citfooterlbl.setForeground(new java.awt.Color(255, 255, 255));
        citfooterlbl.setText("Niño Jay Bueta_Jose Cresnald Cosico - 3IS2");

        javax.swing.GroupLayout citfooterpanelLayout = new javax.swing.GroupLayout(citfooterpanel);
        citfooterpanel.setLayout(citfooterpanelLayout);
        citfooterpanelLayout.setHorizontalGroup(
            citfooterpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(citfooterpanelLayout.createSequentialGroup()
                .addGap(582, 582, 582)
                .addComponent(citfooterlbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        citfooterpanelLayout.setVerticalGroup(
            citfooterpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, citfooterpanelLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(citfooterlbl)
                .addGap(22, 22, 22))
        );

        citpanel1.setBackground(new java.awt.Color(255, 255, 255));

        citlbl1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        citlbl1.setForeground(new java.awt.Color(1, 51, 153));
        citlbl1.setText("College of Industrial Technology");

        citlbl2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        citlbl2.setText("<html>The College of Industrial Technology (CIT)\n                offers technical and vocational programs focusing on applied sciences and hands-on skills \n                needed in industries such as electronics, mechanics, and information systems.</html>");

        javax.swing.GroupLayout citpanel1Layout = new javax.swing.GroupLayout(citpanel1);
        citpanel1.setLayout(citpanel1Layout);
        citpanel1Layout.setHorizontalGroup(
            citpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(citpanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(citpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(citlbl1)
                    .addComponent(citlbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 309, Short.MAX_VALUE)
                .addComponent(citimg, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        citpanel1Layout.setVerticalGroup(
            citpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(citpanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(citpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(citimg, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(citpanel1Layout.createSequentialGroup()
                        .addComponent(citlbl1)
                        .addGap(18, 18, 18)
                        .addComponent(citlbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        citpanel2.setBackground(new java.awt.Color(255, 255, 255));

        citlbl3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        citlbl3.setForeground(new java.awt.Color(1, 51, 153));
        citlbl3.setText("BSIT");

        citlbl4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        citlbl4.setText("Bacherlor of Science in Industrial Technology");

        javax.swing.GroupLayout citpanel2Layout = new javax.swing.GroupLayout(citpanel2);
        citpanel2.setLayout(citpanel2Layout);
        citpanel2Layout.setHorizontalGroup(
            citpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, citpanel2Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(citlbl4)
                .addGap(52, 52, 52))
            .addGroup(citpanel2Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(citlbl3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        citpanel2Layout.setVerticalGroup(
            citpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(citpanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(citlbl3)
                .addGap(93, 93, 93)
                .addComponent(citlbl4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        citpanel3.setBackground(new java.awt.Color(255, 255, 255));
        citpanel3.setPreferredSize(new java.awt.Dimension(410, 292));

        citlbl5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        citlbl5.setForeground(new java.awt.Color(1, 51, 153));
        citlbl5.setText("BTVTED");

        citlbl6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        citlbl6.setText("Bachelor of Technical-Vocational Teacher Education\n");

        javax.swing.GroupLayout citpanel3Layout = new javax.swing.GroupLayout(citpanel3);
        citpanel3.setLayout(citpanel3Layout);
        citpanel3Layout.setHorizontalGroup(
            citpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(citpanel3Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(citpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, citpanel3Layout.createSequentialGroup()
                        .addComponent(citlbl6)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, citpanel3Layout.createSequentialGroup()
                        .addComponent(citlbl5)
                        .addGap(152, 152, 152))))
        );
        citpanel3Layout.setVerticalGroup(
            citpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(citpanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(citlbl5)
                .addGap(98, 98, 98)
                .addComponent(citlbl6)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        citpanel4.setBackground(new java.awt.Color(255, 255, 255));

        citlbl7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        citlbl7.setForeground(new java.awt.Color(1, 51, 153));
        citlbl7.setText("BSAT");

        citlbl8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        citlbl8.setText("Bachelor of Science in Automotive Technology");

        javax.swing.GroupLayout citpanel4Layout = new javax.swing.GroupLayout(citpanel4);
        citpanel4.setLayout(citpanel4Layout);
        citpanel4Layout.setHorizontalGroup(
            citpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(citpanel4Layout.createSequentialGroup()
                .addGroup(citpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(citpanel4Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(citlbl8))
                    .addGroup(citpanel4Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(citlbl7)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        citpanel4Layout.setVerticalGroup(
            citpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(citpanel4Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(citlbl7)
                .addGap(94, 94, 94)
                .addComponent(citlbl8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout citbodypanelLayout = new javax.swing.GroupLayout(citbodypanel);
        citbodypanel.setLayout(citbodypanelLayout);
        citbodypanelLayout.setHorizontalGroup(
            citbodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(citheaderpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(citfooterpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(citbodypanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(citbodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(citpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(citbodypanelLayout.createSequentialGroup()
                        .addComponent(citpanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(citpanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(citpanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        citbodypanelLayout.setVerticalGroup(
            citbodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(citbodypanelLayout.createSequentialGroup()
                .addComponent(citheaderpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(citpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(citbodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(citpanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(citpanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .addComponent(citpanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(citfooterpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(citbodypanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(citbodypanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void citbackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citbackbtnActionPerformed
            FrmMainMenu_Bueta_Cosico main = new FrmMainMenu_Bueta_Cosico();
            main.setVisible(true);
            this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_citbackbtnActionPerformed

    private void citclosebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citclosebtnActionPerformed
         System.exit(0);       // TODO add your handling code here:
    }//GEN-LAST:event_citclosebtnActionPerformed

    private void citminimizebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citminimizebtnActionPerformed
         setState(JFrame.ICONIFIED);      // TODO add your handling code here:
    }//GEN-LAST:event_citminimizebtnActionPerformed
    
    private void addHover(JPanel panel) {
    panel.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseEntered(MouseEvent e) {
            panel.setBackground(ThemeManager.hoverColor); // temporary hover color
            panel.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }

        @Override
        public void mouseExited(MouseEvent e) {
            panel.setBackground(ThemeManager.bodyColor); // revert to current theme color
        }
     });
    }
    

    public class ShadowRoundedPanel extends JPanel {

    private int cornerRadius = 20;
    private int shadowSize = 8;

    public ShadowRoundedPanel(int radius) {
        this.cornerRadius = radius;
        setOpaque(false);
    }

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();

        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        // Shadow
        g2.setColor(new Color(0, 0, 0, 40)); // light shadow
        g2.fillRoundRect(
            shadowSize,
            shadowSize,
            getWidth() - shadowSize,
            getHeight() - shadowSize,
            cornerRadius,
            cornerRadius
        );

        // Main panel
        g2.setColor(getBackground());
        g2.fillRoundRect(
            0,
            0,
            getWidth() - shadowSize,
            getHeight() - shadowSize,
            cornerRadius,
            cornerRadius
        );

        g2.dispose();
        super.paintComponent(g);
       }
    }
    
    private void updateTheme() {
    // Panels
    citheaderpanel.setBackground(ThemeManager.headerColor);
    citbodypanel.setBackground(ThemeManager.bodyColor);
    citfooterpanel.setBackground(ThemeManager.footerColor);

    // Labels
    citlbl1.setForeground(ThemeManager.textColor);
    citlbl2.setForeground(ThemeManager.textColor);
    citlbl3.setForeground(ThemeManager.textColor);
    citlbl4.setForeground(ThemeManager.textColor);
    citlbl5.setForeground(ThemeManager.textColor);
    citlbl6.setForeground(ThemeManager.textColor);
    citlbl7.setForeground(ThemeManager.textColor);
    citlbl8.setForeground(ThemeManager.textColor);
    
    //Panels
    citpanel1.setBackground(ThemeManager.bodyColor);
    citpanel2.setBackground(ThemeManager.bodyColor);
    citpanel3.setBackground(ThemeManager.bodyColor);
    citpanel4.setBackground(ThemeManager.bodyColor);
    
    // Buttons
    citbackbtn.setForeground(ThemeManager.btnColor);
    citminimizebtn.setForeground(ThemeManager.btnColor);
    citclosebtn.setForeground(ThemeManager.btnColor);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmCIT_Bueta_Cosico().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton citbackbtn;
    private javax.swing.JPanel citbodypanel;
    private javax.swing.JButton citclosebtn;
    private javax.swing.JLabel citfooterlbl;
    private javax.swing.JPanel citfooterpanel;
    private javax.swing.JLabel citheaderlbl;
    private javax.swing.JPanel citheaderpanel;
    private javax.swing.JLabel citimg;
    private javax.swing.JLabel citlbl1;
    private javax.swing.JLabel citlbl2;
    private javax.swing.JLabel citlbl3;
    private javax.swing.JLabel citlbl4;
    private javax.swing.JLabel citlbl5;
    private javax.swing.JLabel citlbl6;
    private javax.swing.JLabel citlbl7;
    private javax.swing.JLabel citlbl8;
    private javax.swing.JButton citminimizebtn;
    private javax.swing.JPanel citpanel1;
    private javax.swing.JPanel citpanel2;
    private javax.swing.JPanel citpanel3;
    private javax.swing.JPanel citpanel4;
    // End of variables declaration//GEN-END:variables
}
