/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bueta_cosico_lspunavigation;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.Cursor;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;
import javax.swing.*;
/**
 *
 * @author Shinozaki
 */
public class FrmMainMenu_Bueta_Cosico extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMainMenu_Bueta_Cosico.class.getName());

    /**
     * Creates new form FrmMainMenu_Bueta_Cosico
     */
    public FrmMainMenu_Bueta_Cosico() {
        this.setUndecorated(true);
         initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

         // Apply the current theme at startup
         ThemeManager.applyTheme(ThemeManager.currentTheme);
         updateTheme();

        // Add hover effects to panels
        addHover(ctemainpanel);
        addHover(cbaamainpanel);
        addHover(ccsmainpanel);
        addHover(coemainpanel);
        addHover(citmainpanel);

        // Setup ComboBox action to switch themes
        themecombobox.setSelectedItem(ThemeManager.currentTheme);
        
        themecombobox.addActionListener(e -> {
            String selected = (String) themecombobox.getSelectedItem();
            ThemeManager.applyTheme(selected);
             updateTheme(); // refresh all panel colors
            SwingUtilities.updateComponentTreeUI(this); // ensures repaint
        });
        
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainheaderPanel = new javax.swing.JPanel();
        mainheaderlbl = new javax.swing.JLabel();
        closebtn = new javax.swing.JButton();
        minimizebtn = new javax.swing.JButton();
        themecombobox = new javax.swing.JComboBox<>();
        mainbodyPanel = new javax.swing.JPanel();
        ccsmainpanel = new ShadowRoundedPanel(20);
        ccslbl = new javax.swing.JLabel();
        ccslbl1 = new javax.swing.JLabel();
        ccsopenbtn = new javax.swing.JButton();
        coemainpanel = new ShadowRoundedPanel(20);
        coelbl1 = new javax.swing.JLabel();
        coelbl = new javax.swing.JLabel();
        coeopenbtn = new javax.swing.JButton();
        citmainpanel = new ShadowRoundedPanel(20);
        citlbl = new javax.swing.JLabel();
        citlbl1 = new javax.swing.JLabel();
        citopenbtn = new javax.swing.JButton();
        ctemainpanel = new ShadowRoundedPanel(20);
        ctelbl = new javax.swing.JLabel();
        ctelbl1 = new javax.swing.JLabel();
        cteopenbtn = new javax.swing.JButton();
        mainfooterPanel = new javax.swing.JPanel();
        mainfooterlbl = new javax.swing.JLabel();
        cbaamainpanel = new ShadowRoundedPanel(20);
        cbaalbl1 = new javax.swing.JLabel();
        cbaalbl = new javax.swing.JLabel();
        cbaaopenbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainheaderPanel.setBackground(new java.awt.Color(0, 51, 153));
        mainheaderPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, -10, 0));

        mainheaderlbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        mainheaderlbl.setForeground(new java.awt.Color(255, 255, 255));
        mainheaderlbl.setText("SOME COLLEGES IN LSPU - Bueta_Cosico");

        closebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        closebtn.setForeground(new java.awt.Color(0, 51, 153));
        closebtn.setText("✕");
        closebtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        closebtn.setFocusPainted(false);
        closebtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });

        minimizebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        minimizebtn.setForeground(new java.awt.Color(0, 51, 153));
        minimizebtn.setText("—");
        minimizebtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        minimizebtn.setFocusPainted(false);
        minimizebtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        minimizebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizebtnActionPerformed(evt);
            }
        });

        themecombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Light Blue", "Night Mode", "Nature", "Sunset" }));

        javax.swing.GroupLayout mainheaderPanelLayout = new javax.swing.GroupLayout(mainheaderPanel);
        mainheaderPanel.setLayout(mainheaderPanelLayout);
        mainheaderPanelLayout.setHorizontalGroup(
            mainheaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainheaderPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(mainheaderlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 563, Short.MAX_VALUE)
                .addComponent(themecombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(minimizebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        mainheaderPanelLayout.setVerticalGroup(
            mainheaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainheaderPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(mainheaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainheaderPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(mainheaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(minimizebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(closebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(themecombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(mainheaderlbl))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(mainheaderPanel, java.awt.BorderLayout.PAGE_START);

        ccsmainpanel.setBackground(new java.awt.Color(255, 255, 255));

        ccslbl.setBackground(new java.awt.Color(0, 51, 153));
        ccslbl.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        ccslbl.setForeground(new java.awt.Color(1, 51, 153));
        ccslbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ccslbl.setText("CCS");

        ccslbl1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ccslbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ccslbl1.setText("College Of Computer Studies");

        ccsopenbtn.setBackground(new java.awt.Color(0, 51, 153));
        ccsopenbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ccsopenbtn.setForeground(new java.awt.Color(255, 255, 255));
        ccsopenbtn.setText("Open");
        ccsopenbtn.setFocusPainted(false);
        ccsopenbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ccsopenbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccsopenbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ccsmainpanelLayout = new javax.swing.GroupLayout(ccsmainpanel);
        ccsmainpanel.setLayout(ccsmainpanelLayout);
        ccsmainpanelLayout.setHorizontalGroup(
            ccsmainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ccsmainpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ccsmainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ccsmainpanelLayout.createSequentialGroup()
                        .addComponent(ccsopenbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ccsmainpanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ccslbl1)
                        .addGap(95, 95, 95))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ccsmainpanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(ccslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        ccsmainpanelLayout.setVerticalGroup(
            ccsmainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ccsmainpanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(ccslbl)
                .addGap(67, 67, 67)
                .addComponent(ccslbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(ccsopenbtn)
                .addGap(27, 27, 27))
        );

        coemainpanel.setBackground(new java.awt.Color(255, 255, 255));

        coelbl1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        coelbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coelbl1.setText("College of Engineering");

        coelbl.setBackground(new java.awt.Color(0, 51, 153));
        coelbl.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        coelbl.setForeground(new java.awt.Color(1, 51, 153));
        coelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coelbl.setText("COE");
        coelbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        coeopenbtn.setBackground(new java.awt.Color(0, 51, 153));
        coeopenbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        coeopenbtn.setForeground(new java.awt.Color(255, 255, 255));
        coeopenbtn.setText("Open");
        coeopenbtn.setFocusPainted(false);
        coeopenbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        coeopenbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coeopenbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout coemainpanelLayout = new javax.swing.GroupLayout(coemainpanel);
        coemainpanel.setLayout(coemainpanelLayout);
        coemainpanelLayout.setHorizontalGroup(
            coemainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coemainpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(coemainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(coemainpanelLayout.createSequentialGroup()
                        .addComponent(coeopenbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coemainpanelLayout.createSequentialGroup()
                        .addGap(0, 20, Short.MAX_VALUE)
                        .addGroup(coemainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coemainpanelLayout.createSequentialGroup()
                                .addComponent(coelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coemainpanelLayout.createSequentialGroup()
                                .addComponent(coelbl1)
                                .addGap(121, 121, 121))))))
        );
        coemainpanelLayout.setVerticalGroup(
            coemainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coemainpanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(coelbl)
                .addGap(61, 61, 61)
                .addComponent(coelbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(coeopenbtn)
                .addGap(27, 27, 27))
        );

        citmainpanel.setBackground(new java.awt.Color(255, 255, 255));

        citlbl.setBackground(new java.awt.Color(0, 51, 153));
        citlbl.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        citlbl.setForeground(new java.awt.Color(1, 51, 153));
        citlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        citlbl.setText("CIT");

        citlbl1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        citlbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        citlbl1.setText("College of Industrial Technology");

        citopenbtn.setBackground(new java.awt.Color(0, 51, 153));
        citopenbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        citopenbtn.setForeground(new java.awt.Color(255, 255, 255));
        citopenbtn.setText("Open");
        citopenbtn.setFocusPainted(false);
        citopenbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        citopenbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citopenbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout citmainpanelLayout = new javax.swing.GroupLayout(citmainpanel);
        citmainpanel.setLayout(citmainpanelLayout);
        citmainpanelLayout.setHorizontalGroup(
            citmainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(citmainpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(citmainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, citmainpanelLayout.createSequentialGroup()
                        .addComponent(citopenbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, citmainpanelLayout.createSequentialGroup()
                        .addComponent(citlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
            .addGroup(citmainpanelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(citlbl1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        citmainpanelLayout.setVerticalGroup(
            citmainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(citmainpanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(citlbl)
                .addGap(46, 46, 46)
                .addComponent(citlbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(citopenbtn)
                .addGap(27, 27, 27))
        );

        ctemainpanel.setBackground(new java.awt.Color(255, 255, 255));
        ctemainpanel.setOpaque(false);

        ctelbl.setBackground(new java.awt.Color(0, 51, 153));
        ctelbl.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        ctelbl.setForeground(new java.awt.Color(1, 51, 153));
        ctelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ctelbl.setText("CTE");

        ctelbl1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ctelbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ctelbl1.setText("College of Teacher Education");

        cteopenbtn.setBackground(new java.awt.Color(0, 51, 153));
        cteopenbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cteopenbtn.setForeground(new java.awt.Color(255, 255, 255));
        cteopenbtn.setText("Open");
        cteopenbtn.setFocusPainted(false);
        cteopenbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cteopenbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cteopenbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ctemainpanelLayout = new javax.swing.GroupLayout(ctemainpanel);
        ctemainpanel.setLayout(ctemainpanelLayout);
        ctemainpanelLayout.setHorizontalGroup(
            ctemainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ctemainpanelLayout.createSequentialGroup()
                .addGroup(ctemainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ctemainpanelLayout.createSequentialGroup()
                        .addGroup(ctemainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ctemainpanelLayout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(ctelbl1))
                            .addGroup(ctemainpanelLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(ctelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ctemainpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cteopenbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ctemainpanelLayout.setVerticalGroup(
            ctemainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ctemainpanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(ctelbl)
                .addGap(59, 59, 59)
                .addComponent(ctelbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cteopenbtn)
                .addGap(26, 26, 26))
        );

        mainfooterPanel.setBackground(new java.awt.Color(0, 51, 153));
        mainfooterPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 25, 15, 25));
        mainfooterPanel.setLayout(new java.awt.BorderLayout());

        mainfooterlbl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        mainfooterlbl.setForeground(new java.awt.Color(255, 255, 255));
        mainfooterlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainfooterlbl.setText("Niño Jay Bueta, Jose Cresnald Cosico - 3IS2");
        mainfooterPanel.add(mainfooterlbl, java.awt.BorderLayout.PAGE_START);

        cbaamainpanel.setBackground(new java.awt.Color(255, 255, 255));

        cbaalbl1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbaalbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cbaalbl1.setText("College of Business Administration and Accountancy");

        cbaalbl.setBackground(new java.awt.Color(0, 51, 153));
        cbaalbl.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        cbaalbl.setForeground(new java.awt.Color(1, 51, 153));
        cbaalbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cbaalbl.setText("CBAA");

        cbaaopenbtn.setBackground(new java.awt.Color(0, 51, 153));
        cbaaopenbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbaaopenbtn.setForeground(new java.awt.Color(255, 255, 255));
        cbaaopenbtn.setText("Open");
        cbaaopenbtn.setFocusPainted(false);
        cbaaopenbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cbaaopenbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbaaopenbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cbaamainpanelLayout = new javax.swing.GroupLayout(cbaamainpanel);
        cbaamainpanel.setLayout(cbaamainpanelLayout);
        cbaamainpanelLayout.setHorizontalGroup(
            cbaamainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cbaamainpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cbaamainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cbaamainpanelLayout.createSequentialGroup()
                        .addComponent(cbaaopenbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cbaamainpanelLayout.createSequentialGroup()
                        .addGap(0, 40, Short.MAX_VALUE)
                        .addComponent(cbaalbl, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cbaamainpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbaalbl1)
                .addGap(33, 33, 33))
        );
        cbaamainpanelLayout.setVerticalGroup(
            cbaamainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cbaamainpanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(cbaalbl)
                .addGap(51, 51, 51)
                .addComponent(cbaalbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbaaopenbtn)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout mainbodyPanelLayout = new javax.swing.GroupLayout(mainbodyPanel);
        mainbodyPanel.setLayout(mainbodyPanelLayout);
        mainbodyPanelLayout.setHorizontalGroup(
            mainbodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainfooterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainbodyPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(mainbodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbaamainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ctemainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73)
                .addGroup(mainbodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainbodyPanelLayout.createSequentialGroup()
                        .addComponent(coemainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(ccsmainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(citmainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        mainbodyPanelLayout.setVerticalGroup(
            mainbodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainbodyPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(mainbodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ccsmainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(coemainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ctemainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(mainbodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbaamainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(citmainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(mainfooterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(mainbodyPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_closebtnActionPerformed

    private void minimizebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizebtnActionPerformed
        setState(JFrame.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_minimizebtnActionPerformed

    private void cteopenbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cteopenbtnActionPerformed
        FrmCTE_Bueta_Cosico cte = new FrmCTE_Bueta_Cosico();
        cte.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_cteopenbtnActionPerformed

    private void coeopenbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coeopenbtnActionPerformed
        FrmCOE_Bueta_Cosico coe = new FrmCOE_Bueta_Cosico();
        coe.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_coeopenbtnActionPerformed

    private void ccsopenbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccsopenbtnActionPerformed
        FrmCCS_Bueta_Cosico ccs = new FrmCCS_Bueta_Cosico();
        ccs.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_ccsopenbtnActionPerformed

    private void cbaaopenbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbaaopenbtnActionPerformed
       FrmCBAA_Bueta_Cosico coe = new FrmCBAA_Bueta_Cosico();
       coe.setVisible(true);
       this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_cbaaopenbtnActionPerformed

    private void citopenbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citopenbtnActionPerformed
       FrmCIT_Bueta_Cosico cit = new FrmCIT_Bueta_Cosico();
       cit.setVisible(true);
       this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_citopenbtnActionPerformed
    
    private void addHover(JPanel panel) {
    panel.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseEntered(MouseEvent e) {
            panel.setBackground(ThemeManager.hoverColor); // temporary hover color
            panel.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }

        @Override
        public void mouseExited(MouseEvent e) {
            panel.setBackground(ThemeManager.bodyColor); // revert to current theme color
        }
     });
    }


    

    public class ShadowRoundedPanel extends JPanel {

    private int cornerRadius = 20;
    private int shadowSize = 8;

    public ShadowRoundedPanel(int radius) {
        this.cornerRadius = radius;
        setOpaque(false);
    }

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();

        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        // Shadow
        g2.setColor(new Color(0, 0, 0, 40)); // light shadow
        g2.fillRoundRect(
            shadowSize,
            shadowSize,
            getWidth() - shadowSize,
            getHeight() - shadowSize,
            cornerRadius,
            cornerRadius
        );

        // Main panel
        g2.setColor(getBackground());
        g2.fillRoundRect(
            0,
            0,
            getWidth() - shadowSize,
            getHeight() - shadowSize,
            cornerRadius,
            cornerRadius
        );

        g2.dispose();
        super.paintComponent(g);
       }
    }
    
    
    
    private void updateTheme() {
    // Header, body, footer
    mainheaderPanel.setBackground(ThemeManager.headerColor);
    mainbodyPanel.setBackground(ThemeManager.bodyColor); // unified body color
    mainfooterPanel.setBackground(ThemeManager.footerColor);

    // Header/footer text
    mainheaderlbl.setForeground(ThemeManager.whitetextColor);
    mainfooterlbl.setForeground(ThemeManager.whitetextColor);

    // Panels
    ctemainpanel.setBackground(ThemeManager.bodyColor);
    cbaamainpanel.setBackground(ThemeManager.bodyColor);
    coemainpanel.setBackground(ThemeManager.bodyColor);
    ccsmainpanel.setBackground(ThemeManager.bodyColor);
    citmainpanel.setBackground(ThemeManager.bodyColor);

    // Buttons
    cteopenbtn.setBackground(ThemeManager.btnColor);
    coeopenbtn.setBackground(ThemeManager.btnColor);
    ccsopenbtn.setBackground(ThemeManager.btnColor);
    cbaaopenbtn.setBackground(ThemeManager.btnColor);
    citopenbtn.setBackground(ThemeManager.btnColor);

    // Labels
    ccslbl.setForeground(ThemeManager.textColor);
    ccslbl1.setForeground(ThemeManager.textColor);
    ctelbl.setForeground(ThemeManager.textColor);
    ctelbl1.setForeground(ThemeManager.textColor);
    citlbl.setForeground(ThemeManager.textColor);
    citlbl1.setForeground(ThemeManager.textColor);
    cbaalbl.setForeground(ThemeManager.textColor);
    cbaalbl1.setForeground(ThemeManager.textColor);
    coelbl.setForeground(ThemeManager.textColor);
    coelbl1.setForeground(ThemeManager.textColor);

    // Close/Minimize buttons
    minimizebtn.setForeground(ThemeManager.btnColor);
    closebtn.setForeground(ThemeManager.btnColor);
    }


    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMainMenu_Bueta_Cosico().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cbaalbl;
    private javax.swing.JLabel cbaalbl1;
    private javax.swing.JPanel cbaamainpanel;
    private javax.swing.JButton cbaaopenbtn;
    private javax.swing.JLabel ccslbl;
    private javax.swing.JLabel ccslbl1;
    private javax.swing.JPanel ccsmainpanel;
    private javax.swing.JButton ccsopenbtn;
    private javax.swing.JLabel citlbl;
    private javax.swing.JLabel citlbl1;
    private javax.swing.JPanel citmainpanel;
    private javax.swing.JButton citopenbtn;
    private javax.swing.JButton closebtn;
    private javax.swing.JLabel coelbl;
    private javax.swing.JLabel coelbl1;
    private javax.swing.JPanel coemainpanel;
    private javax.swing.JButton coeopenbtn;
    private javax.swing.JLabel ctelbl;
    private javax.swing.JLabel ctelbl1;
    private javax.swing.JPanel ctemainpanel;
    private javax.swing.JButton cteopenbtn;
    private javax.swing.JPanel mainbodyPanel;
    private javax.swing.JPanel mainfooterPanel;
    private javax.swing.JLabel mainfooterlbl;
    private javax.swing.JPanel mainheaderPanel;
    private javax.swing.JLabel mainheaderlbl;
    private javax.swing.JButton minimizebtn;
    private javax.swing.JComboBox<String> themecombobox;
    // End of variables declaration//GEN-END:variables
}
